name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:
    name: "Publish to Github Package Registry"
    runs-on: ubuntu-latest
    steps:
      -
        uses: actions/checkout@v1
      -
        uses: actions/setup-node@v1
        with:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
          always-auth: true
          node-version: 12
          registry-url: "https://npm.pkg.github.com"
          scope: olegkoval
      -
        env:
          CI: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: "npm ci --unsafe-perm"
      -
        env:
          CI: true
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        run: |
            echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" > /home/runner/work/_temp/.npmrc
            echo "//registry.npmjs.org/:_authToken=$GITHUB_TOKEN" >> /home/runner/work/_temp/.npmrc
            npx semantic-release
